#!/usr/bin/python

import string,os,re,sys
import ntt
from optparse import OptionParser

description="> make friging mask"
usage= "%prog  listframes"

if __name__ == "__main__":
     parser = OptionParser(usage=usage,description=description,version="%prog 1.0")
     parser.add_option("-i", "--interactive",dest="interactive",action="store_true")
     parser.add_option("-c", "--combine",dest="combine",default='average',type="str",
                  help='type of combination \t [%default]')
     parser.add_option("-r", "--rejection",dest="rejection",default='avsigclip',type="str",
                  help='type of rejection \t [%default]')
     parser.add_option("-o", "--output",dest="output",default='',type="str",
                  help=' output fringing mask name   \t [%default]')
     (option, args) = parser.parse_args()

     if len(args) < 1:
         sys.argv.append('--help')
         option,args = parser.parse_args()

     if option.interactive==None:  _interactive=False
     else:                         _interactive=True
     _rejection=option.rejection
     _combine=option.combine
     _output=option.output
     files=ntt.util.readlist(args[0])
     output=ntt.efosccalibdef.makefringingmask(files,_output,_interactive,_combine='average',_rejection='avsigclip')
     ntt.util.phase3header(img)  #  phase 3 definitions
     ntt.util.airmass(img)  #  phase 3 definitions
     ntt.util.updateheader(img,0,{'quality':['Final','']})
     print('\n###fringing file= '+str(output))
